### ISSUE TITLE
crash in some SCTE-35 packet in v.2.2.37

### ISSUE THREAD

**Issue by richard-vd** [futzu/threefive#11]
I haven't yet found the the exact packet data leading to this crash. Here is the traceback:
```Traceback (most recent call last):
  File "./mcastc.py", line 74, in <module>
    read_stream(mcast_sock)
  File "./mcastc.py", line 50, in read_stream
    ts.decode()
  File "./mcastc.py", line 35, in decode
    cue = self._parser(pkt)
  File "/usr/local/lib/python3.6/site-packages/threefive/stream.py", line 173, in _parser
    return self._parse_scte35(pkt, pid)
  File "/usr/local/lib/python3.6/site-packages/threefive/stream.py", line 208, in _parse_scte35
    return Cue(pkt, packet_data)
  File "/usr/local/lib/python3.6/site-packages/threefive/cue.py", line 59, in __init__
    self._parse(payload)
  File "/usr/local/lib/python3.6/site-packages/threefive/cue.py", line 64, in _parse
    payload = self._mk_descriptors(payload)
  File "/usr/local/lib/python3.6/site-packages/threefive/cue.py", line 92, in _mk_descriptors
    self._descriptorloop(payload, dll)
  File "/usr/local/lib/python3.6/site-packages/threefive/cue.py", line 103, in _descriptorloop
    spliced = self._set_splice_descriptor(payload)
  File "/usr/local/lib/python3.6/site-packages/threefive/cue.py", line 181, in _set_splice_descriptor
    spliced.decode(bitbin)
  File "/usr/local/lib/python3.6/site-packages/threefive/segmentation.py", line 102, in decode
    self._set_segmentation(bitbin) 
  File "/usr/local/lib/python3.6/site-packages/threefive/segmentation.py", line 128, in _set_segmentation
    self.segmentation_upid_type = bitbin.asint(8)  # 1 byte
  File "/usr/local/lib/python3.6/site-packages/bitn.py", line 20, in asint
    return (self.bits >> (self.idx)) & ~(~0 << num_bits)
ValueError: negative shift count   
```

**Comment by richard-vd** [comment]
There seems to be an issue with handling messages that are spread over multiple TS packets.

It crashes on a large SCTE-35 section. The decode() function works correctly if I feed it these 200 bytes directly, so the issue is not with the SCTE-35 decoding itself.
```
from threefive import decode

hexed = "0xFC30C500000000000000FFF00506FFDC2BC19C00AF023F43554549000000007FBF0C3053425342360C017C740E86A4000000D3E91000000000004E69484A7072374D354C4E0000000000000000000000000000010000021743554549000000007FBF0808000000A2AE9555A1210303021743554549000000007FBF0808000000A2AE9524C4110303021C43554549000000007FFF000A4AAFB00808000000A4860E747C100102021C43554549000000007FFF0003CB5B300808000000A4860E8DE92001021B17BC54"

decode(hexed)
```
Due to the size the SCTE-35 section is split over two TS packets. The first TS packet contains the first 183 bytes and the following TS packet contains the remaining 17 bytes.

**Comment by futzu** [comment]
SCTE 35 shouldn't be spread over more than one packet, should it? 
I'll look it up.
Try this to print the packet
```python3
# make this my.py
#
# python3 my.py video.ts

import sys
from threefive import Stream


class MyStream(Stream):

    def _parse_scte35(self, pkt, pid):
        print(pkt)
        super()._parse_scte35(pkt,pid)



if __name__ == '__main__':
    with open(sys.argv[1],'rb') as tsdata:
        mystream = MyStream(tsdata)
        mystream.decode()

 
```

**Comment by futzu** [comment]
I was wrong. A single cue can be 4096 bytes.
Ill try to fix it today

**Comment by futzu** [comment]
Use this and post the output for me please
```python3
import sys
from threefive import Stream


class MyStream(Stream):

    def _parse_scte35(self, pkt, pid):
        print(pkt)

if __name__ == '__main__':
    with open(sys.argv[1],'rb') as tsdata:
        mystream = MyStream(tsdata)
        mystream.decode()

 ```

**Comment by futzu** [comment]
This may work.
```python3
import sys
from threefive import Stream, Cue
from threefive.tools import mk_payload

'''
    exp.py


    python3 exp.py video.ts
    
'''
class ExpCue(Cue):
    
    def __init__(self, data, packet_data=None):
        self.info_section = None
        self.command = None
        self.descriptors = []
        self.payload = mk_payload(data)
        self.packet_data = packet_data

    def decode(self):
        self._parse(self.payload)


class ExpStream(Stream):
    
    def __init__(self, tsdata, show_null=False):
        super().__init__(tsdata, show_null=False)
        self.cue = None

    def _parse_scte35(self, pkt, pid):
        print(pkt)
        if not self.cue:
            packet_data = self._mk_packet_data(pid)
            if pkt[18] in self._CMD_TYPES:
                self.cue = ExpCue(pkt,packet_data)
                self.cue.decode()
        else:
            self.cue.payload += pkt[5:]   

        if self.cue.info_section.section_length <= len(self.cue.payload)+3:
                cue = self.cue
                self.cue = None
                return cue
        else:
            return False

if __name__ == '__main__':
    with open(sys.argv[1],'rb') as tsdata:
        exp = ExpStream(tsdata)
        exp.decode()

 
```

**Comment by futzu** [comment]
This may work.

```python3
import sys
from threefive import Stream, Cue
from threefive.tools import mk_payload, to_stderr

"""
    exp2.py


    python3 exp2.py video.ts
    
"""


class ExpCue(Cue):
    def __init__(self, data, packet_data=None):
        self.info_section = None
        self.command = None
        self.descriptors = []
        self.payload = mk_payload(data)
        self.packet_data = packet_data

    def decode(self):
        self._parse(self.payload)


class ExpStream(Stream):
    def __init__(self, tsdata, show_null=False):
        super().__init__(tsdata, show_null=False)
        self.cue = None

    def _parse_scte35(self, pkt, pid):
        print(pkt)
        if not self.cue:
            packet_data = self._mk_packet_data(pid)
            if pkt[18] in self._CMD_TYPES:
                self.cue = ExpCue(pkt, packet_data)
                self.cue._mk_info_section(pkt[5:19])
                to_stderr(f"Cue Length: {self.cue.info_section.section_length+3} Bytes")
        else:
            self.cue.payload += pkt[5:]
            to_stderr(f"Payload Length: {len(self.cue.payload)} Bytes")
        if (self.cue.info_section.section_length + 3) <= len(self.cue.payload):
            self.cue.decode()
            cue = self.cue
            self.cue = None
            return cue
        else:
            return False


if __name__ == "__main__":
    with open(sys.argv[1], "rb") as tsdata:
        exp = ExpStream(tsdata)
        exp.decode()
```

**Comment by futzu** [comment]
This might work.
```python3
import sys
from threefive import Stream, Cue
from threefive.tools import mk_payload, to_stderr

"""
    exp3.py


    python3 exp3.py video.ts
    
"""


class ExpCue(Cue):
    def __init__(self, data, packet_data=None):
        self.info_section = None
        self.command = None
        self.descriptors = []
        self.payload = mk_payload(data)
        self.packet_data = packet_data

    def decode(self):
        self._parse(self.payload)


class ExpStream(Stream):
    def __init__(self, tsdata, show_null=False):
        super().__init__(tsdata, show_null=False)
        self.cue = None

    def _parse_scte35(self, pkt, pid):
        print(pkt)
        if not self.cue:
            packet_data = self._mk_packet_data(pid)
            if pkt[18] in self._CMD_TYPES:
                self.cue = ExpCue(pkt, packet_data)
                self.cue._mk_info_section(pkt[5:19])
                to_stderr(f"Cue Length: {self.cue.info_section.section_length+3} Bytes")
            else:
                return False
        else:
            self.cue.payload += pkt[5:]
            to_stderr(f"Payload Length: {len(self.cue.payload)} Bytes")
        if (self.cue.info_section.section_length + 3) <= len(self.cue.payload):
            self.cue.decode()
            cue = self.cue
            self.cue = None
            return cue
        else:
            return False


if __name__ == "__main__":
    with open(sys.argv[1], "rb") as tsdata:
        exp = Stream(tsdata)
        exp.decode()

 
```

**Comment by futzu** [comment]
### Where are you man? 
**I think we might have a fix,  I rolled it into 2.2.39.** 


2.2.39 
- [x]  Everything works
- [ ]  Most of it works
- [ ]  Some of it works
- [ ]  None of it works

**Comment by richard-vd** [comment]
It works using 2.2.39, and better than ever!

Thank you so much Adrian!  I could not have done it as well as you did.

```
$ python3.6 git/SCTE35-threefive/examples/Proxy_Demo.py SCTE35-20201206-1552-crash.ts >/dev/null
{
  "info_section": {
    "table_id": "0xfc",
    "section_syntax_indicator": false,
    "private": false,
    "reserved": "0x3",
    "section_length": 197,
    "protocol_version": 0,
    "encrypted_packet": false,
    "encryption_algorithm": 0,
    "pts_adjustment": 0.0,
    "cw_index": "0x0",
    "tier": "0xfff",
    "splice_command_length": 5,
    "splice_command_type": 6,
    "descriptor_loop_length": 175,
    "crc": "0x1b17bc54"
  },
  "command": {
    "time_specified_flag": true,
    "pts_time": 88764.693644,
    "name": "Time Signal",
    "splice_command_length": 5
  },
  "descriptors": [
    {
      "tag": 2,
      "identifier": "CUEI",
      "name": "Segmentation Descriptor",
      "segmentation_event_id": "0x0",
      "segmentation_event_cancel_indicator": false,
      "components": [],
      "program_segmentation_flag": true,
      "segmentation_duration_flag": false,
      "delivery_not_restricted_flag": true,
      "segmentation_message": "Content Identification",
      "segmentation_upid_type": 12,
      "segmentation_upid_length": 48,
      "segmentation_upid": "MPU:{'format identifier': 1396855618, 'private data': 1936820078441672404473053425261908680439762377525455429835714289939492683913409725141830833076766714626048}",
      "segmentation_type_id": 1,
      "segment_num": 0,
      "segments_expected": 0,
      "descriptor_length": 63
    },
    {
      "tag": 2,
      "identifier": "CUEI",
      "name": "Segmentation Descriptor",
      "segmentation_event_id": "0x0",
      "segmentation_event_cancel_indicator": false,
      "components": [],
      "program_segmentation_flag": true,
      "segmentation_duration_flag": false,
      "delivery_not_restricted_flag": true,
      "segmentation_message": "Chapter End",
      "segmentation_upid_type": 8,
      "segmentation_upid_length": 8,
      "segmentation_upid": "AiringID:0xa2ae9555a1",
      "segmentation_type_id": 33,
      "segment_num": 3,
      "segments_expected": 3,
      "descriptor_length": 23
    },
    {
      "tag": 2,
      "identifier": "CUEI",
      "name": "Segmentation Descriptor",
      "segmentation_event_id": "0x0",
      "segmentation_event_cancel_indicator": false,
      "components": [],
      "program_segmentation_flag": true,
      "segmentation_duration_flag": false,
      "delivery_not_restricted_flag": true,
      "segmentation_message": "Program End",
      "segmentation_upid_type": 8,
      "segmentation_upid_length": 8,
      "segmentation_upid": "AiringID:0xa2ae9524c4",
      "segmentation_type_id": 17,
      "segment_num": 3,
      "segments_expected": 3,
      "descriptor_length": 23
    },
    {
      "tag": 2,
      "identifier": "CUEI",
      "name": "Segmentation Descriptor",
      "segmentation_event_id": "0x0",
      "segmentation_event_cancel_indicator": false,
      "components": [],
      "program_segmentation_flag": true,
      "segmentation_duration_flag": true,
      "delivery_not_restricted_flag": true,
      "segmentation_duration": 1918.52,
      "segmentation_message": "Program Start",
      "segmentation_upid_type": 8,
      "segmentation_upid_length": 8,
      "segmentation_upid": "AiringID:0xa4860e747c",
      "segmentation_type_id": 16,
      "segment_num": 1,
      "segments_expected": 2,
      "descriptor_length": 28
    },
    {
      "tag": 2,
      "identifier": "CUEI",
      "name": "Segmentation Descriptor",
      "segmentation_event_id": "0x0",
      "segmentation_event_cancel_indicator": false,
      "components": [],
      "program_segmentation_flag": true,
      "segmentation_duration_flag": true,
      "delivery_not_restricted_flag": true,
      "segmentation_duration": 707.32,
      "segmentation_message": "Chapter Start",
      "segmentation_upid_type": 8,
      "segmentation_upid_length": 8,
      "segmentation_upid": "AiringID:0xa4860e8de9",
      "segmentation_type_id": 32,
      "segment_num": 1,
      "segments_expected": 2,
      "descriptor_length": 28
    }
  ],
  "pid": 3842,
  "program": 1
}
```

**Comment by futzu** [comment]
You spelled out the problem,
I just followed what you said.

I'm glad that worked.
