### ISSUE TITLE
Private Command decoding calculates command length incorrectly, causes Exception

### ISSUE THREAD

**Issue by davemevans** [futzu/threefive#112]
```
>>> import threefive
>>> cue = threefive.Cue("/DAdAAAAAAAAAP/wDP8AvGFOZGVhZGJlZWYAABizs+c=")
>>> cue.decode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/davide/work/oss/scte35-threefive/threefive/cue.py", line 90, in decode
    crc = hex(int.from_bytes(bites[0:4], byteorder="big"))
                             ~~~~~^^^^^
TypeError: 'NoneType' object is not subscriptable
```

The current method in `PrivateCommand.decode`  doesn't work because when it is called `self.bites` contains the remainder of the cue unparsed up til that point ie it has the descriptor loop length, descriptors and crc. The length is set incorrectly, and this causes the remaining decoding to fail.

As an aside, the identifier length is also incorrect (should 32 bits).

**Comment by futzu** [comment]
Firstly, where did you get the Base64 Cue? 
Secondly, give me a minute to figure it out.... :)

**Comment by futzu** [comment]
Does your patch fix this one?

**Comment by davemevans** [comment]
Sadly not. I genuinely don't know how to solve this other than by trusting the splice_command_length. But even then it can be set to 0xFFF and then you're out of luck again.

**Comment by futzu** [comment]
first , you rarely see private commands, 
second, I don't many 0xFFF lengths  these days.

Here's what I'm thinking, 

In cue.py I will set it  from info_section for all the Splice Commands BEFORE they run decode, and then after decode I will set the info_secrtion command length from the command command length, since all the rest of the commands can calculate their own length.
So in PrivateCommand don't set a command_length, will just keep the info_section length. 

```py3
 def _set_splice_command(self, bites):
        """
        Cue._set_splice_command parses
        the command section of a SCTE35 cue.
        """
        sct = self.info_section.splice_command_type
        if sct not in command_map:
            return False
        self.command = command_map[sct](bites)
        self.command.command_length=self.info_section.splice_command_length  # <---- set it from info section 
        self.command.decode()
        del self.command.bites
        self.info_section.splice_command_length = self.command.command_length # <---- set it from command
        bites = bites[self.command.command_length :]
        return bites

```

**Comment by davemevans** [comment]
Love it :+1:

**Comment by futzu** [comment]
It's close, the extra 6 bytes on the end is probably descriptor loop length and crc
```py3
a@fu:~/build/SCTE35_threefive$ pypy3
Python 3.9.16 (7.3.11+dfsg-2+deb12u2, May 20 2024, 22:08:06)
[PyPy 7.3.11 with GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> from threefive import Cue, PrivateCommand
>>>> pc = PrivateCommand()\
.... 
.... 
>>>> pc.identifier= int.from_bytes(b'ABCD',byteorder="big")
>>>> pc.private_bytes=b'AdrianofDOOM'
>>>> cue=Cue()
>>>> cue.command =pc
>>>> cue.encode()
'/DAhAAAAAAAAAP/wEP9BQkNEQWRyaWFub2ZET09NAAA9zmva'
>>>> cue.xml()
b'AdrianofDOOM\x00\x00=\xcek\xda'
<SpliceInfoSection xmlns="https://scte.org/schemas/35" ptsAdjustment="0" protocolVersion="0" sapType="3" tier="4095">
   <PrivateCommand identifier="1094861636">
      <PrivateBytes>b'AdrianofDOOM\x00\x00=\xcek\xda'</PrivateBytes>
   </PrivateCommand>
</SpliceInfoSection>

```

**Comment by futzu** [comment]
Now it works . 

```py3
>>>> from threefive import Cue, PrivateCommand
>>>> pc = PrivateCommand()
.... 
.... 
>>>> pc.identifier= int.from_bytes(b'ABCD',byteorder="big")
>>>> pc.private_bytes=b'AdrianofDOOM'
>>>> cue=Cue()
>>>> cue.command =pc
>>>> cue.encode()
'/DAhAAAAAAAAAP/wEP9BQkNEQWRyaWFub2ZET09NAAA9zmva'
>>>> cue.xml()
b'AdrianofDOOM'
<SpliceInfoSection xmlns="https://scte.org/schemas/35" ptsAdjustment="0" protocolVersion="0" sapType="3" tier="4095">
   <PrivateCommand identifier="1094861636">
      <PrivateBytes>b'AdrianofDOOM'</PrivateBytes>
   </PrivateCommand>
</SpliceInfoSection>

```

**Comment by futzu** [comment]
Now, it works.

```py3
>>>> from threefive import Cue, PrivateCommand
>>>> pc = PrivateCommand()
>>>> pc.identifier= int.from_bytes(b'ABCD',byteorder="big")
>>>> pc.private_bytes=b'AdrianofDOOM'
>>>> cue=Cue()
>>>> cue.command =pc
>>>> cue.encode()
'/DAhAAAAAAAAAP/wEP9BQkNEQWRyaWFub2ZET09NAAA9zmva'
>>>> cue.xml()
b'AdrianofDOOM'
<SpliceInfoSection xmlns="https://scte.org/schemas/35" ptsAdjustment="0" protocolVersion="0" sapType="3" tier="4095">
   <PrivateCommand identifier="1094861636">
      <PrivateBytes>AdrianofDOOM</PrivateBytes>
   </PrivateCommand>
</SpliceInfoSection>

```

**Comment by davemevans** [comment]
Almost! Something weird is happening if you put a descriptor on the end - see the CUEI:

```
>>> import threefive
>>> cue = threefive.Cue()
>>> cue.command = threefive.PrivateCommand()
>>> cue.command.identifier = 12345678
>>> cue.command.private_bytes = b'test'
>>> d = threefive.descriptors.AvailDescriptor()
>>> d.provider_avail_id = 9876
>>> cue.descriptors.append(d)
>>> cue.xml()
<SpliceInfoSection xmlns="https://scte.org/schemas/35" ptsAdjustment="0" protocolVersion="0" sapType="3" tier="4095">
   <PrivateCommand identifier="12345678">
      <PrivateBytes>test
CUEI</PrivateBytes>
   </PrivateCommand>
   <AvailDescriptor providerAvailId="9876"/>
</SpliceInfoSection>
```

**Comment by futzu** [comment]
That is weird...... hmmmm it has to be coming of the avail descriptor , I got to run out for  while , I'll hit when I get back.

**Comment by futzu** [comment]
The bites are not aligned correctly, that is happening when a cue is encoded. I'll sort it out tonight, hopefully . 
We are super close , great job man.

```py3
>>>> ad.provider_avail_id=1223435
>>>> ad.encode()
b'CUEI\x00\x12\xab\x0b'
>>>> cue.descriptors.append(ad)
>>>> cue.encode()
'/DArAAAAAAAAAP/wEP9BQkNEQWRyaWFub2ZET09NAAoACENVRUkAEqsLlX8/mw=='
>>>> cue.xml()
b'AdrianofDOOM\x00\n\x00\x08CUEI\x00\x12'
<SpliceInfoSection xmlns="https://scte.org/schemas/35" ptsAdjustment="0" protocolVersion="0" sapType="3" tier="4095">
   <PrivateCommand identifier="1094861636">
      <PrivateBytes>AdrianofDOOM
CUEI</PrivateBytes>
   </PrivateCommand>
   <AvailDescriptor providerAvailId="1223435"/>
</SpliceInfoSection>
```

**Comment by futzu** [comment]
# Boom goes the dynamite.



```py3
from threefive import Cue,PrivateCommand,AvailDescriptor

cue=Cue()

pc = PrivateCommand()
pc.identifier= int.from_bytes(b'ABCD',byteorder="big")
pc.private_bytes=b'yoyo'

ad =AvailDescriptor()
ad.provider_avail_id=37

cue.command=pc
cue.descriptors.append(ad)

cue.encode()
cue.show()
print(cue.xml())

```




```xml


<SpliceInfoSection xmlns="https://scte.org/schemas/35" ptsAdjustment="0" protocolVersion="0" sapType="3" tier="4095">
   <PrivateCommand identifier="1094861636">
      <PrivateBytes>yoyo</PrivateBytes>
   </PrivateCommand>
   <AvailDescriptor providerAvailId="37"/>
</SpliceInfoSection>

```

**Comment by davemevans** [comment]
Nice one! One last thing I was thinking about over night: what if private_bytes needs to be something like

```
cue.command.private_bytes = b'\x00\x01\x02\x03'
```

I think this will currently result in `<PrivateBytes></PrivateBytes>`?

Maybe it isn't worth all this effort for a little used feature ...

Edit: looking at the spec, it's supposed to be hexbinary representation of the byte, so maybe just a `.hex()` on those bites and ship it?

**Comment by futzu** [comment]
"Maybe it isn't worth all this effort for a little used feature ..."

Oh no, we're not stopping now, we are in way too deep. :)

I just did another commit, a found a few more bugs.
 The good news is  I've fixed a bunch of problematic code in cue.py
that hadn't been touched in years and was kind of janky
 
Do  you want to take over PrivateCommand for a while  and sort the private_bytes?
I need to take a shower. 

By the way, thanks again for helping out, I really appreciate it. 

We are doing well. pylint score is 9.77 and  cyclomatic complexity is  at 2.06

### git pull

**Comment by futzu** [comment]
Really, Private Command wasn't the problem, today none of my changes were in commands.py, it was mostly cue.py.

**Comment by futzu** [comment]
There is still something wrong with cue.bites, the descriptors are off when I parse streams
