### ISSUE TITLE
Error encoding Mid()

### ISSUE THREAD

**Issue by ramastat** [futzu/threefive#121]
Running into an issue when encoding messages that of the Mid descriptor.  I can use this B64 and decode with no issues
/DA1AAAAAAAAAP/wBQb+9Or5gAAfAh1DVUVJAAAAAT+/DQ4DDEFCQ0QxMjM0NTY3SCIBAbbL/pQ=

When trying to encode the same message I get this error:

```
>>> cue.encode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python\Python311\Lib\site-packages\threefive\cue.py", line 249, in encode
    dscptr_bites = self._unloop_descriptors()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\site-packages\threefive\cue.py", line 311, in _unloop_descriptors
    dbite_chunks = [dsptr.encode() for dsptr in self.descriptors]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\site-packages\threefive\cue.py", line 311, in <listcomp>
    dbite_chunks = [dsptr.encode() for dsptr in self.descriptors]
                    ^^^^^^^^^^^^^^
  File "D:\Python\Python311\Lib\site-packages\threefive\descriptors.py", line 413, in encode
    self._encode_segmentation(nbin)
  File "D:\Python\Python311\Lib\site-packages\threefive\descriptors.py", line 454, in _encode_segmentation
    the_upid.encode(nbin, self.segmentation_upid)
  File "D:\Python\Python311\Lib\site-packages\threefive\upids.py", line 232, in encode
    the_upid.encode(nbin)
TypeError: Upid.encode() missing 1 required positional argument: 'seg_upid'
```

In the encode method for Mid(), it is only passing nbin in the the_upid.encode() call causing the encode to fail

**Comment by futzu** [comment]
Sorry about that, I thought I fixed all those.  I blame xml :). I made a bunch of changes for xml, and then had to undo them because they didn't work.You're completely correct it's missing the one arg. I'll do a build either tonight or tomorrow and have that corrected. 
I appreciate you letting me know. 

Adrian

**Comment by futzu** [comment]
So I update the encode method and it works.
This will encode __to xml__ but I still need to work out 
the __from_xml__ 

```py3
    def encode(self, nbin, seg_upid):
        """
        encode Mid Upid
        """
        for mid_upid in seg_upid:
            nbin.add_int(mid_upid["upid_type"], 8)
            nbin.add_int(mid_upid["upid_length"], 8)
            the_upid = upid_map[mid_upid["upid_type"]][1](
                None, mid_upid["upid_type"], mid_upid["upid_length"]
            )
            the_upid.encode(nbin, mid_upid["segmentation_upid"])
```




```rebol
a@fu:~/build/SCTE35_threefive$ threefive  encode hex ' /DA1AAAAAAAAAP/wBQb+9Or5gAAfAh1DVUVJAAAAAT+/DQ4DDEFCQ0QxMjM0NTY3SCIBAbbL/pQ='
0xfc303500000000000000fff00506fef4eaf980001f021d43554549000000013fbf0d0e030c414243443132333435363748220101b6cbfe94



a@fu:~/build/SCTE35_threefive$ threefive encode xml ' /DA1AAAAAAAAAP/wBQb+9Or5gAAfAh1DVUVJAAAAAT+/DQ4DDEFCQ0QxMjM0NTY3SCIBAbbL/pQ='
<SpliceInfoSection xmlns="https://scte.org/schemas/35" ptsAdjustment="0" protocolVersion="0" sapType="3" tier="4095">
   <TimeSignal>
      <SpliceTime ptsTime="4109040000"/>
   </TimeSignal>
   <!-- Break Start -->
   <SegmentationDescriptor segmentationEventId="1" segmentationEventCancelIndicator="false" segmentationEventIdComplianceIndicator="false" segmentationTypeId="34" segmentNum="1" segmentsExpected="1">
      <!-- UPID: MID -->
      <SegmentationUpid segmentationUpidType="3" name="AdID">ABCD1234567H</SegmentationUpid>
   </SegmentationDescriptor>
</SpliceInfoSection>

a@fu:~/build/SCTE35_threefive$


```

**Comment by futzu** [comment]
pip up to v2.4.85 and you should be good.

**Comment by ramastat** [comment]
Awesome. Thank you for the quick response and update.
