### ISSUE TITLE
Issue with UTF-8 Error

### ISSUE THREAD

**Issue by ffmv30** [futzu/threefive#35]
Hi,

Encountering a utf-8 error when splice command type is 6 - time signal. 

Sample error message:

UnicodeDecodeError: “utf-8’ codec can’t decode byte 0xd0 in position 1: invalid continuation byte

**Comment by futzu** [comment]
```>>>> cue =threefive.Cue('/DBBAAAAAAAA///wBQb/fe82YAArAilDVUVJAAAAAH+/DBpWTU5VAdD3rHrUzxHnv9QAJrlBTzAB+olIUQEAAAzazmo')
>>>> cue.decode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/a/threefive/threefive/cue.py", line 62, in decode
    after_info = self.mk_info_section(self.bites)
  File "/home/a/threefive/threefive/cue.py", line 167, in mk_info_section
    self.info_section.decode(info_bites)
  File "/home/a/threefive/threefive/section.py", line 46, in decode
    bitbin = BitBin(bites)
  File "/home/a/threefive/threefive/bitn.py", line 20, in __init__
    self.bits = int.from_bytes(bites, byteorder="big")
TypeError: cannot convert a (unicode) str object to bytes
```
So I tried it as bytes
``` 
>>>> cue =threefive.Cue(b'/DBBAAAAAAAA///wBQb/fe82YAArAilDVUVJAAAAAH+/DBpWTU5VAdD3rHrUzxHnv9QAJrlBTzAB+olIUQEAAAzazmo')
>>>> cue.decode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/a/threefive/threefive/cue.py", line 62, in decode
    after_info = self.mk_info_section(self.bites)
  File "/home/a/threefive/threefive/cue.py", line 167, in mk_info_section
    self.info_section.decode(info_bites)
  File "/home/a/threefive/threefive/section.py", line 50, in decode
    ("splice_info_section.table_id should be 0xfc Not: ", self.table_id)
ValueError: ('splice_info_section.table_id should be 0xfc Not: ', '0x2f')
```
As bytes it decodes but the table ID is incorrect. 
Where did you get this?

**Comment by futzu** [comment]
I found the issue.
The base64 encoding is off.
 
```
>>>> from base64 import b64decode
>>>> b64decode('/DBBAAAAAAAA///wBQb/fe82YAArAilDVUVJAAAAAH+/DBpWTU5VAdD3rHrUzxHnv9QAJrlBTzAB+olIUQEAAAzazmo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/pypy3/lib-python/3/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
>>>> 
```

**Comment by ffmv30** [comment]
Thanks for the update!
Sorry there was actually a typo when I posted the original sample message, it was missing a "=" character at the end. 

The actual sample base 64 encoded message should be: 
/DBBAAAAAAAA///wBQb/fe82YAArAilDVUVJAAAAAH+/DBpWTU5VAdD3rHrUzxHnv9QAJrlBTzAB+olIUQEAAAzazmo=

Still getting the UTF-8 error with the above message.

**Comment by futzu** [comment]
Okay that makes more sense.It's a bug for sure.  threefive is blowing up on the in the MPU Segmentation Upid. Give me a minute to figure out it and Ill fix it.

**Comment by futzu** [comment]
pip it up to 2.2.99. 

```
a@fumatica:~/threefive$ pypy3
Python 3.7.10 (7.3.5+dfsg-2, Jun 03 2021, 20:39:46)
[PyPy 7.3.5 with GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.

>>>> from threefive import version
>>>> version()
2.2.99
>>>> from threefive import Cue
>>>> cue=Cue('/DBBAAAAAAAA///wBQb/fe82YAArAilDVUVJAAAAAH+/DBpWTU5VAdD3rHrUzxHnv9QAJrlBTzAB+olIUQEAAAzazmo=')
>>>> cue.decode()
True
>>>> cue.show()
{
      "info_section": {
            "table_id": "0xfc",
            "section_syntax_indicator": false,
            "private": false,
            "sap_type": "0x3",
            "sap_details": "No Sap Type",
            "section_length": 65,
            "protocol_version": 0,
            "encrypted_packet": false,
            "encryption_algorithm": 0,
            "pts_adjustment": 0.0,
            "cw_index": "0xff",
            "tier": "0xfff",
            "splice_command_length": 5,
            "splice_command_type": 6,
            "descriptor_loop_length": 43,
            "crc": "0xcdace6a"
      },
      "command": {
            "calculated_length": 5,
            "name": "Time Signal",
            "time_specified_flag": true,
            "pts_time": 71197.736889
      },
      "descriptors": [
            {
                  "tag": 2,
                  "descriptor_length": 41,
                  "name": "Segmentation Descriptor",
                  "identifier": "CUEI",
                  "components": [],
                  "segmentation_event_id": "0x0",
                  "segmentation_event_cancel_indicator": false,
                  "program_segmentation_flag": true,
                  "segmentation_duration_flag": false,
                  "delivery_not_restricted_flag": true,
                  "segmentation_message": "Content Identification",
                  "segmentation_upid_type": 12,
                  "segmentation_upid_type_name": "MPU",
                  "segmentation_upid_length": 26,
                  "segmentation_upid": {
                        "format_identifier": "0x564d4e55",
                        "private_data": "0x1d0f7ac7ad4cf11e7bfd40026b9414f3001fa894851"
                  },
                  "segmentation_type_id": 1,
                  "segment_num": 0,
                  "segments_expected": 0
            }
      ]
}
>>>> 
```

**Comment by futzu** [comment]
https://github.com/futzu/threefive/releases/tag/v.2.2.99

**Comment by futzu** [comment]
Here's where the bug is 
```
"segmentation_upid": {
                        "format_identifier": "0x564d4e55",
                        "private_data": "0x1d0f7ac7ad4cf11e7bfd40026b9414f3001fa894851"      <----- This is what was blowing up.
                  },
```

I was decoding private_data to ascii, since bytes are not allowed in JSON... in python. 
So I changed it to decode private_data to a hex string, __and I'm pretty sure that is not the spec, 
but I wanted to get you up and running with something while I check the spec and stuff__.

Is this cool for you?

**Comment by futzu** [comment]
> The Spec says:

![SCTE-35-mpu-upid](https://user-images.githubusercontent.com/52701496/130718942-cd1bf334-9ff8-48eb-b01e-5cf30330953f.png)
