### ISSUE TITLE
Issues with example scripts

### ISSUE THREAD

**Issue by pizzafridayisathing** [futzu/threefive#68]
Firstly, super many thanks for these tools, amazing work!

Similar to [Issue26](https://github.com/futzu/scte35-threefive/issues/26), I really want the preroll, but most of the example scripts I get various errors for. 

**cue_list_too.py seems the only one I can get working** 
```
$ pypy3 cue_list_too.py cam-scte-out.ts
{
    "info_section": {
        "table_id": "0xfc",
...truncated
```

**But not cue_list.py**  
```
$ pypy3 cue_list.py cam-scte-out.ts
Traceback (most recent call last):
  File "cue_list.py", line 34, in <module>
    for cue in do():
  File "cue_list.py", line 25, in do
    cue = strm.decode_next()
  File "/home/me/.local/lib/pypy3.6/site-packages/threefive/stream.py", line 206, in decode_next
    cue = self.decode(func=False)
  File "/home/me/.local/lib/pypy3.6/site-packages/threefive/stream.py", line 170, in decode
    if not self._find_start():
  File "/home/me/.local/lib/pypy3.6/site-packages/threefive/stream.py", line 154, in _find_start
    one = self._tsdata.read(1)
ValueError: read of closed file

```

**Comment by futzu** [comment]
Some of those are kind of old, here's preroll.py

```python3
"""

Shows preroll using PCR and PTS
for the time of the SCTE-35 packet.
"""

import sys
from threefive import Stream


def show_preroll(cue):
    """
    show_preroll shows preroll times with pcr and pts.
    """
    if cue.command.pts_time:
        if cue.packet_data:
            two = f" Splice Time: {cue.command.pts_time} Preroll:"
            if cue.packet_data.pcr:
                pcr_preroll = cue.command.pts_time - cue.packet_data.pcr
                two += f" (PCR): {round(pcr_preroll,6)}"
            if cue.packet_data.pts:
                pts_preroll = cue.command.pts_time - cue.packet_data.pts
                two += f" (PTS): {round(pts_preroll,6)}"
            print(two)


def do():
    """
    do processes multiple command line args
    """
    args = sys.argv[1:]
    for arg in args:
        print(f"file: {arg}")
        strm = Stream(arg, show_null=False)
        strm.decode(func=show_preroll)


if __name__ == "__main__":
    do()
```

**Comment by futzu** [comment]
cue_list.py
```python3
"""
Example using Stream.decode() with a custom function
to return a list of cues from a video

Usage:

pypy3 cue_list.py video.ts

"""


import sys
from threefive import Stream, Cue

# A list to hold cues 
CUES=[]

def cue_func(cue):
    """
    threefive.Stream.decode cqn be passed in a
    custom function that accepts a Cue as the only arg.
    this is an example of a custom function.

    """
    CUES.append(cue)
    cue.show()


def do():
    """
    do collects a list of Cues  from a Stream
    """
    arg = sys.argv[1]
    strm = Stream(arg)
    strm.decode(func=cue_func) # cue_func is the custom function from above


if __name__ == "__main__":
    do()
    [print(cue.command.name,cue.encode()) for cue in CUES]
```

**Comment by futzu** [comment]
Did you have any other example problems?

**Comment by pizzafridayisathing** [comment]
Thanks for getting back :) 

It seems like these are the only two so far, (I've just tested a few more (but not ALL) and it seems they're mostly good) 

I don't have mplayer installed and figure that might take me a while, so unable to test those

**Comment by futzu** [comment]
Cool.

You know you don't have to use mplayer, any player that can read from stdin will work.

**Comment by pizzafridayisathing** [comment]
Apologies if I've misunderstood, but just to confirm, are you saying that preroll.py and cue_list.py are known as not to work, or should they be working?
