### ISSUE TITLE
IndexError thrown in _decode_components() threefive/commands.py:217

### ISSUE THREAD

**Issue by marksaxer-cbs** [futzu/threefive#79]
The list is empty upon initialization. A loop then attempts to assign indexes of the empty list

Thrown from threefive/commands.py:217
```
    def _decode_components(self, bitbin):
        """
        SpliceInsert._decode_components loops
        over SpliceInsert.components,
        and is called from SpliceInsert.decode()
        """
        self.component_count = bitbin.as_int(8)
        self.components = []
        for i in range(0, self.component_count):
>           self.components[i] = bitbin.as_int(8)
E           IndexError: list assignment index out of range
```

The request that triggered the error
```
% python3               
Python 3.11.2 (main, Feb 16 2023, 02:55:59) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from threefive import SpliceInsert
>>> bites = b'\xfc0%\x00\x00\x00\x03(\x98\x00\xff\xf0\x14\x05d-\xe5Y\x7f\xef\xfe\x00\x1a\xea\xa0\xfe\x00Re\xc0\x00\x01\x01\x01\x00\x00\x88\x8c\xc9\xed'
>>> SpliceInsert(bites).decode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/threefive/commands.py", line 190, in decode
    self._decode_components(bitbin)
  File "/opt/homebrew/lib/python3.11/site-packages/threefive/commands.py", line 217, in _decode_components
    self.components[i] = bitbin.as_int(8)
    ~~~~~~~~~~~~~~~^^^
IndexError: list assignment index out of range
```

A possible fix
```
    def _decode_components(self, bitbin):
        """ 
        SpliceInsert._decode_components loops
        over SpliceInsert.components,
        and is called from SpliceInsert.decode()
        """
        self.component_count = bitbin.as_int(8)
        self.components = [bitbin.as_int(8) for _ in range(0, self.component_count)]
```

A similar error is expected to be thrown at threefive/commands.py:339 as well

**Comment by futzu** [comment]
I'm kind of confused as to how you came up with that in the first place.

You are trying to decode the entire Cue as just a Splice Insert.

```py3
a@debian:~/build/clean/scte35-threefive$ pypy3
Python 3.9.16 (7.3.11+dfsg-2, Feb 06 2023, 16:52:03)
[PyPy 7.3.11 with GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> from threefive import Cue,SpliceInsert
>>>> bites = b'\xfc0%\x00\x00\x00\x03(\x98\x00\xff\xf0\x14\x05d-\xe5Y\x7f\xef\\
xfe\x00\x1a\xea\xa0\xfe\x00Re\xc0\x00\x01\x01\x01\x00\x00\x88\x8c\xc9\xed'
>>>> cue = Cue(bites)
>>>> cue.decode()
True
>>>> cue.show()
{
    "info_section": {
        "table_id": "0xfc",
        "section_syntax_indicator": false,
        "private": false,
        "sap_type": "0x3",
        "sap_details": "No Sap Type",
        "section_length": 37,
        "protocol_version": 0,
        "encrypted_packet": false,
        "encryption_algorithm": 0,
        "pts_adjustment_ticks": 207000,
        "pts_adjustment": 2.3,
        "cw_index": "0x0",
        "tier": "0xfff",
        "splice_command_length": 20,
        "splice_command_type": 5,
        "descriptor_loop_length": 0,
        "crc": "0x888cc9ed"
    },
    "command": {
        "command_length": 20,
        "command_type": 5,
        "name": "Splice Insert",
        "time_specified_flag": true,
        "pts_time": 19.6,
        "pts_time_ticks": 1764000,
        "break_auto_return": true,
        "break_duration": 60.0,
        "break_duration_ticks": 5400000,
        "splice_event_id": 1680729433,
        "splice_event_cancel_indicator": false,
        "out_of_network_indicator": true,
        "program_splice_flag": true,
        "duration_flag": true,
        "splice_immediate_flag": false,
        "unique_program_id": 1,
        "avail_num": 1,
        "avail_expected": 1
    },
    "descriptors": []
}
>>>> 

```
* To just decode a Splice Insert Command by itself, only pass in the command bytes. 

```py3
>>>> si bites = b'd-\xe5Y\x7f\xef\xfe\x00\x1a\xea\xa0\xfe\x00Re\xc0\x00\x01\x01\x01'
 
>>>> si = SpliceInsert(si_bites)
>>>> si.decode()
>>>> si
{'command_length': 20, 'command_type': 5, 'name': 'Splice Insert', 'bites': b'd-\xe5Y\x7f\xef\xfe\x00\x1a\xea\xa0\xfe\x00Re\xc0\x00\x01\x01\x01', 'time_specified_flag': True, 'pts_time': 19.6, 'pts_time_ticks': 1764000, 'break_auto_return': True, 'break_duration': 60.0, 'break_duration_ticks': 5400000, 'splice_event_id': 1680729433, 'splice_event_cancel_indicator': False, 'out_of_network_indicator': True, 'program_splice_flag': True, 'duration_flag': True, 'splice_immediate_flag': False, 'component_count': None, 'components': None, 'unique_program_id': 1, 'avail_num': 1, 'avail_expected': 1}

```

Does that make sense?

**Comment by marksaxer-cbs** [comment]
I see. Thank you for the reply. I misunderstood the `bites` value associated with the Cue object and incorrectly assumed I could pass that byte string into the SpliceInsert constructor. Taking another look at the Cue object, it is clear to me that the SpliceCommand is already decoded and can read from `Cue.command`.

**Comment by futzu** [comment]
Mark, what encoding your scte-35?  Is it Amazon?
I keep seeing this 
`  "pts_adjustment": 2.3`
all over the place and you had it too. 
I am thinking that's a bug.

**Comment by marksaxer-cbs** [comment]
I do not recall if the example I posted was encoded via AWS ML, but it is very likely it was. Below is a decoded scte35 that was encoded via AWS ML

```
[
  {
    "bites": b
    "\xfc0.\x00\x00\x00\x03(\x98\x00\xff\xf0\x05\x06\xfe\x00\x0b\xfeP\x00\x18\x02\x16CUEIdW\xe4\x91\x7f\xcb\x00\x00Re\xc0\x00\x004\x00\x00\x00\x00j[\xbc\x14" ,
    "info_section": {
      "table_id": "0xfc" ,
      "section_syntax_indicator": False ,
      "private": False ,
      "sap_type": "0x3" ,
      "sap_details": "No Sap Type" ,
      "section_length": 46 ,
      "protocol_version": 0 ,
      "encrypted_packet": False ,
      "encryption_algorithm": 0 ,
      "pts_adjustment_ticks": 207000 ,
      "pts_adjustment": 2.3 ,
      "cw_index": "0x0" ,
      "tier": "0xfff" ,
      "splice_command_length": 5 ,
      "splice_command_type": 6 ,
      "descriptor_loop_length": 24 ,
      "crc": "0x6a5bbc14"
    } ,
    "command": {
      "command_length": 5 ,
      "command_type": 6 ,
      "name": "Time Signal" ,
      "time_specified_flag": True ,
      "pts_time": 8.733333 ,
      "pts_time_ticks": 786000
    } ,
    "descriptors": [
      {
        "tag": 2 ,
        "descriptor_length": 22 ,
        "name": "Segmentation Descriptor" ,
        "identifier": "CUEI" ,
        "provider_avail_id": None ,
        "components": [] ,
        "segmentation_event_id": "0x6457e491" ,
        "segmentation_event_cancel_indicator": False ,
        "component_count": None ,
        "program_segmentation_flag": True ,
        "segmentation_duration_flag": True ,
        "delivery_not_restricted_flag": False ,
        "web_delivery_allowed_flag": False ,
        "no_regional_blackout_flag": True ,
        "archive_allowed_flag": False ,
        "device_restrictions": "No Restrictions" ,
        "segmentation_duration": 60.0 ,
        "segmentation_duration_ticks": 5400000 ,
        "segmentation_message": "Provider Placement Opportunity Start" ,
        "segmentation_upid_type": 0 ,
        "segmentation_upid_type_name": "No UPID" ,
        "segmentation_upid_length": 0 ,
        "segmentation_upid": None ,
        "segmentation_type_id": 52 ,
        "segment_num": 0 ,
        "segments_expected": 0 ,
        "sub_segment_num": 0 ,
        "sub_segments_expected": 0
      }
    ] ,
    "packet_data": None
  }
]
```

**Comment by futzu** [comment]
Thanks for replying man, I appreciate it. 
Since talking with you about the sub_segment stuff, I've been seeing it excluded a lot lately,

* Did you add the `sub_segment_num ` and `sub_segments_expected` vars yourself? 

I've also noticed a `pts_adjustment` of 2.3 seconds in a lot of the same  SCTE-35. 
According to the spec, if present, `pts_adjustment`  should be added to `pts_time` in Splice Inserts and TimeSignals. I'm trying to figure out if that  2.3 is intentional, or not. 

* Do you use the 2.3 second `pts_adjustment`? 
* Are you SCTE-35 splice points where you want them?

**Comment by futzu** [comment]
I just pushed v.2.3.85, it will add those sub_segment_num and sub_segment expected for you, if they are not there.
