### ISSUE TITLE
unable to re-encode the following base64 /DA8AAAAAAAAAP/wBQb/ZoaJUwAmAiRDVUVJBPpHwH/9AABSY2IMEERJU0NTTURDMDc3MzAwTEg0AQESS6TU

### ISSUE THREAD

**Issue by lshaked74** [futzu/threefive#81]
I'm trying to re-encode a signal after modifying pts value without touching any of the descriptors
I have no issues with several segmentation_type_id 48 that I've tried but for some reason I can't re-encode the following one (segmentation type id 52) - /DA8AAAAAAAAAP/wBQb/ZoaJUwAmAiRDVUVJBPpHwH/9AABSY2IMEERJU0NTTURDMDc3MzAwTEg0AQESS6TU

```
Traceback (most recent call last):
  File "/Users/lshaked/scte35/./scte35processor.py", line 24, in <module>
    sig_binary_data = new_cue.encode()
  File "/Users/lshaked/scte35/lib/python3.9/site-packages/threefive/cue.py", line 210, in encode
    dscptr_bites = self._unloop_descriptors()
  File "/Users/lshaked/scte35/lib/python3.9/site-packages/threefive/cue.py", line 262, in _unloop_descriptors
    dbite_chunks = [dsptr.encode() for dsptr in self.descriptors]
  File "/Users/lshaked/scte35/lib/python3.9/site-packages/threefive/cue.py", line 262, in <listcomp>
    dbite_chunks = [dsptr.encode() for dsptr in self.descriptors]
  File "/Users/lshaked/scte35/lib/python3.9/site-packages/threefive/descriptors.py", line 335, in encode
    self._encode_segmentation(nbin)
  File "/Users/lshaked/scte35/lib/python3.9/site-packages/threefive/descriptors.py", line 381, in _encode_segmentation
    self._encode_segments(nbin)
  File "/Users/lshaked/scte35/lib/python3.9/site-packages/threefive/descriptors.py", line 394, in _encode_segments
    self._chk_var(int, nbin.add_int, "sub_segment_num", 8)  # 1 byte
  File "/Users/lshaked/scte35/lib/python3.9/site-packages/threefive/base.py", line 104, in _chk_var
    raise ValueError(err_mesg)
ValueError: sub_segment_num is not set, it should be type <class 'int'>
```

here is the new_cue before encode:
```
{'bites': None, 'info_section': {'table_id': '0xfc', 'section_syntax_indicator': False, 'private': False, 'sap_type': '0x3', 'sap_details': 'No Sap Type', 'section_length': 60, 'protocol_version': 0, 'encrypted_packet': False, 'encryption_algorithm': 0, 'pts_adjustment_ticks': 0, 'pts_adjustment': 0.0, 'cw_index': '0x0', 'tier': '0xfff', 'splice_command_length': 5, 'splice_command_type': 6, 'descriptor_loop_length': 38, 'crc': '0x124ba4d4'}, 'command': {'command_length': 5, 'command_type': 6, 'name': 'Time Signal', 'bites': None, 'time_specified_flag': True, 'pts_time': 66834.03677777777, 'pts_time_ticks': 6015063310}, 'descriptors': [{'tag': 2, 'descriptor_length': 36, 'name': 'Segmentation Descriptor', 'identifier': 'CUEI', 'bites': None, 'provider_avail_id': None, 'components': [], 'segmentation_event_id': '0x4fa47c0', 'segmentation_event_cancel_indicator': False, 'component_count': None, 'program_segmentation_flag': True, 'segmentation_duration_flag': True, 'delivery_not_restricted_flag': True, 'web_delivery_allowed_flag': None, 'no_regional_blackout_flag': None, 'archive_allowed_flag': None, 'device_restrictions': None, 'segmentation_duration': 59.993267, 'segmentation_duration_ticks': 5399394, 'segmentation_message': 'Provider Placement Opportunity Start', 'segmentation_upid_type': 12, 'segmentation_upid_type_name': 'MPU', 'segmentation_upid_length': 16, 'segmentation_upid': {'format_identifier': 1145656131, 'private_data': '0x534d44433037373330304c48'}, 'segmentation_type_id': 52, 'segment_num': 1, 'segments_expected': 1, 'sub_segment_num': None, 'sub_segments_expected': None}], 'packet_data': None}
```

code is:
```
import threefive
from threefive import Cue

sig_binary_data="/DA8AAAAAAAAAP/wBQb/ZoaJUwAmAiRDVUVJBPpHwH/9AABSY2IMEERJU0NTTURDMDc3MzAwTEg0AQESS6TU" # doesn't work
#sig_binary_data="/DA8AAAAAAAAAP/wBQb+TiMTvgAmAiRDVUVJBRjPQX/9AAELyNwMEERJU0MxMDAzMDI0Nl85OTkwAQEAQHzt" # works PA start
#sig_binary_data="/DA8AAAAAAAAAP/wBQb/Xz380gAmAiRDVUVJBPpG2X/9AADN+HUMEERJU0MxMDAzNTk2N185OTkwAQE1K48T" # works
scte_35_cue = threefive.Cue(sig_binary_data)
scte_35_cue.decode()
print(scte_35_cue)
print(scte_35_cue.descriptors[0].sub_segment_num,"\n")
scte_35_dict = scte_35_cue.get()
for x in scte_35_dict['descriptors'][0].keys():
    print("key:",x,"value:",scte_35_dict['descriptors'][0][x])
print(scte_35_dict['descriptors'][0].keys())
print("signal pts_time",scte_35_dict['command']['pts_time_ticks'])
recorded_pts_time = scte_35_dict['command']['pts_time_ticks'] + 3003
print("new pts",str(recorded_pts_time))
#scte_35_dict['command']['pts_time_ticks'] = recorded_pts_time
#scte_35_dict['command']['pts_time'] = float(recorded_pts_time/90000)
new_cue = threefive.Cue()
new_cue.load(scte_35_dict)
print(new_cue)
sig_binary_data = new_cue.encode()
print(sig_binary_data)
```
using latest version - 2.3.81

**Comment by futzu** [comment]
Your Cue is incomplete.

I believe you're missing sub_segment_num and sub_segments_expected .

This is from the SegmentationDescriptor class
```py3
      def _decode_segments(self, bitbin):
        self.segment_num = bitbin.as_int(8)  # 1 byte
        self.segments_expected = bitbin.as_int(8)  # 1 byte
        if self.segmentation_type_id in [0x34, 0x36, 0x38, 0x3A]:    
            self.sub_segment_num = bitbin.as_int(8)  # 1 byte
            self.sub_segments_expected = bitbin.as_int(8)  # 1 byte
```

before the encode yours were set to 
```py3
 'sub_segment_num': None, 'sub_segments_expected': None
```
That's why you got an error when encoding.

```js
`ValueError: sub_segment_num is not set, it should be type <class 'int'>`
```

I really don't  enforce rules on decoding, for backward compatibility,  but I do on encoding.





```lua
a@debian:~/umzz$ threefive '/DA8AAAAAAAAAP/wBQb/ZoaJUwAmAiRDVUVJBPpHwH/9AABSY2IMEERJU0NTTURDMDc3MzAwTEg0AQESS6TU'
8 bits requested, but only 0 bits left.       <--- This means 8 bits should have been read but they were not available.

 bytes remaining: b'' 
8 bits requested, but only 0 bits left.     <--- This means 8 bits should have been read but they were not available.

 bytes remaining: b'' 
{
    "info_section": {
        "table_id": "0xfc",
        "section_syntax_indicator": false,
        "private": false,
        "sap_type": "0x3",
        "sap_details": "No Sap Type",
        "section_length": 60,
        "protocol_version": 0,
        "encrypted_packet": false,
        "encryption_algorithm": 0,
        "pts_adjustment_ticks": 0,
        "pts_adjustment": 0.0,
        "cw_index": "0x0",
        "tier": "0xfff",
        "splice_command_length": 5,
        "splice_command_type": 6,
        "descriptor_loop_length": 38,
        "crc": "0x124ba4d4"
    },
    "command": {
        "command_length": 5,
        "command_type": 6,
        "name": "Time Signal",
        "time_specified_flag": true,
        "pts_time": 66834.003411,
        "pts_time_ticks": 6015060307
    },
    "descriptors": [
        {
            "tag": 2,
            "descriptor_length": 36,
            "name": "Segmentation Descriptor",
            "identifier": "CUEI",
            "components": [],
            "segmentation_event_id": "0x4fa47c0",
            "segmentation_event_cancel_indicator": false,
            "program_segmentation_flag": true,
            "segmentation_duration_flag": true,
            "delivery_not_restricted_flag": true,
            "segmentation_duration": 59.993267,
            "segmentation_duration_ticks": 5399394,
            "segmentation_message": "Provider Placement Opportunity Start",
            "segmentation_upid_type": 12,
            "segmentation_upid_type_name": "MPU",
            "segmentation_upid_length": 16,
            "segmentation_upid": {
                "format_identifier": 1145656131,
                "private_data": "0x534d44433037373330304c48"
            },
            "segmentation_type_id": 52,
            "segment_num": 1,
            "segments_expected": 1
        }
    ]
}
```

**Comment by futzu** [comment]
![image](https://user-images.githubusercontent.com/52701496/232960583-63287822-acdf-497e-b081-83b0de6cf929.png)

**Comment by lshaked74** [comment]
Hey Adrian, I owe you a beer or a drink of your choice. I've added the code to check if incoming signal isn't following the 2022 spec from this perspective then:
```
scte_35_dict['descriptors'][0]['sub_segment_num']=0
scte_35_dict['descriptors'][0]['sub_segments_expected']=0
```

**Comment by futzu** [comment]
I was going to say, if you aren't using it just set it to zero, but you already figured that out. :)

Glad it worked out for you man,
Adrian

**Comment by futzu** [comment]
I keep seeing this issue all over the place, 
What is encoding your SCTE-35? 
Because this is a bug on their end.

**Comment by lshaked74** [comment]
The specific encoder vendor was not shared. But I agree the issue starts with the signal from the encoder.
