### ISSUE TITLE
Unparseable hex

### ISSUE THREAD

**Issue by wabiloo** [futzu/threefive#98]
Hi there,

I have a stream from MediaLive/MediaPackage that contains the following: 0xFC303B00003BE1341800FFF00506FE00505D700025022343554549000000027FD10000A4D990120D48656C6C6F2C20576F726C64213400000000592280ED

Threefive does not appear to be able to parse it.

In case it helps, it is from a TS file that was generated with TSduck, by inserting the following SCTE information:

```
<?xml version="1.0" encoding="UTF-8"?>
<tsduck>
    <!-- Event 2 - Start -->
    <splice_information_table protocol_version="0" pts_adjustment="0" tier="0x0FFF">
        <time_signal pts_time="5,400,000"/>
        <splice_avail_descriptor identifier="0x43554549" provider_avail_id="0x00000012" />
        <splice_segmentation_descriptor segmentation_event_id="0x00000002"
            web_delivery_allowed="true"
            no_regional_blackout="false"
            archive_allowed="false"
            device_restrictions="1"
            segmentation_duration="10,803,600"
            segmentation_type_id="0x34"
            segment_num="0"
            segments_expected="0"
            sub_segment_num="0"
            sub_segments_expected="0">
            <segmentation_upid type="0x12">
                48656c6c6f2c20576f726c6421
            </segmentation_upid>
        </splice_segmentation_descriptor>
    </splice_information_table>
    <splice_information_table>
        <time_signal/>
      </splice_information_table>

</tsduck>
```

**Comment by wabiloo** [comment]
My bad, wrong upid type. Should have been 0x0C

**Comment by futzu** [comment]
I was just about to tell you that.  The command line tool swallows a lot of the errors, but if you run it the python shell
```py3
>>> cue =threefive.Cue("0xFC303B00003BE1341800FFF00506FE00505D700025022343554549000000027FD10000A4D990120D48656C6C6F2C20576F726C64213400000000592280ED")
>>> cue.decode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/a/.local/lib/python3.11/site-packages/threefive/cue.py", line 73, in decode
    bites = self._mk_descriptors(bites)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a/.local/lib/python3.11/site-packages/threefive/cue.py", line 167, in _mk_descriptors
    self._descriptor_loop(bites[:dll])
  File "/home/a/.local/lib/python3.11/site-packages/threefive/cue.py", line 85, in _descriptor_loop
    spliced = splice_descriptor(loop_bites)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/a/.local/lib/python3.11/site-packages/threefive/descriptors.py", line 482, in splice_descriptor
    spliced.decode()
  File "/home/a/.local/lib/python3.11/site-packages/threefive/descriptors.py", line 342, in decode
    self._decode_segmentation(bitbin)
  File "/home/a/.local/lib/python3.11/site-packages/threefive/descriptors.py", line 362, in _decode_segmentation
    the_upid = upid_map[self.segmentation_upid_type][1](
               ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 18
>>> 
```

Tsduck should have not encoded that,  
But I should probably add something to pass it through, and just return bytes if it doesn't know the UPID type.
I need to add that , I'll try to do it today.

**Comment by wabiloo** [comment]
no urgency from my end, I corrected my mistake

**Comment by futzu** [comment]
four lines changed  and it works:
```py3
>>> import threefive
>>> cue =threefive.Cue("0xFC303B00003BE1341800FFF00506FE00505D700025022343554549000000027FD10000A4D990120D48656C6C6F2C20576F726C64213400000000592280ED")
>>> cue.decode()
True
>>> cue.show()
{
    "info_section": {
        "table_id": "0xfc",
        "section_syntax_indicator": false,
        "private": false,
        "sap_type": "0x03",
        "sap_details": "No Sap Type",
        "section_length": 59,
        "protocol_version": 0,
        "encrypted_packet": false,
        "encryption_algorithm": 0,
        "pts_adjustment_ticks": 1004614680,
        "pts_adjustment": 11162.385333,
        "cw_index": "0x00",
        "tier": "0x0fff",
        "splice_command_length": 5,
        "splice_command_type": 6,
        "descriptor_loop_length": 37,
        "crc": "0x592280ed"
    },
    "command": {
        "command_length": 5,
        "command_type": 6,
        "name": "Time Signal",
        "time_specified_flag": true,
        "pts_time": 58.52,
        "pts_time_ticks": 5266800
    },
    "descriptors": [
        {
            "tag": 2,
            "descriptor_length": 35,
            "name": "Segmentation Descriptor",
            "identifier": "CUEI",
            "segmentation_event_id": "0x02",
            "segmentation_event_cancel_indicator": false,
            "segmentation_event_id_compliance_indicator": true,
            "program_segmentation_flag": true,
            "segmentation_duration_flag": true,
            "delivery_not_restricted_flag": false,
            "web_delivery_allowed_flag": true,
            "no_regional_blackout_flag": false,
            "archive_allowed_flag": false,
            "device_restrictions": "Restrict Group 1",
            "segmentation_duration": 120.04,
            "segmentation_duration_ticks": 10803600,
            "segmentation_message": "Provider Placement Opportunity Start",
            "segmentation_upid_type": 18,
            "segmentation_upid_type_name": "Unknown",
            "segmentation_upid_length": 13,
            "segmentation_upid": "Hello, World!",
            "segmentation_type_id": 52,
            "segment_num": 0,
            "segments_expected": 0,
            "sub_segment_num": 0,
            "sub_segments_expected": 0
        }
    ]
}
>>> 
```
```

**Comment by futzu** [comment]
I hate xml , but threefive will take json 

I just did a build 2.4.49  if you pip up to that you can load JSON and then encode it like this 


```py3
jason ='''{
    "info_section": {
        "table_id": "0xfc",
        "section_syntax_indicator": false,
        "private": false,
        "sap_type": "0x03",jason ='''{
    "info_section": {
        "table_id": "0xfc",
        "section_syntax_indicator": false,
        "private": false,
        "sap_type": "0x03",
        "sap_details": "No Sap Type",
        "section_length": 59,
        "protocol_version": 0,
        "encrypted_packet": false,
        "encryption_algorithm": 0,
        "pts_adjustment_ticks": 1004614680,
        "pts_adjustment": 11162.385333,
        "cw_index": "0x00",
        "tier": "0x0fff",
        "splice_command_length": 5,
        "splice_command_type": 6,
        "descriptor_loop_length": 37,
        "crc": "0x592280ed"
    },
    "command": {
        "command_length": 5,
        "command_type": 6,
        "name": "Time Signal",
        "time_specified_flag": true,
        "pts_time": 58.52,
        "pts_time_ticks": 5266800
    },
    "descriptors": [
        {
            "tag": 2,
            "descriptor_length": 35,
            "name": "Segmentation Descriptor",
            "identifier": "CUEI",
            "segmentation_event_id": "0x02",
            "segmentation_event_cancel_indicator": false,
            "segmentation_event_id_compliance_indicator": true,
            "program_segmentation_flag": true,
            "segmentation_duration_flag": true,
            "delivery_not_restricted_flag": false,
            "web_delivery_allowed_flag": true,
            "no_regional_blackout_flag": false,
            "archive_allowed_flag": false,
            "device_restrictions": "Restrict Group 1",
            "segmentation_duration": 120.04,
            "segmentation_duration_ticks": 10803600,
            "segmentation_message": "Provider Placement Opportunity Start",
            "segmentation_upid_type": 18,
            "segmentation_upid_type_name": "Unknown",
            "segmentation_upid_length": 13,
            "segmentation_upid": "Hello, World!",
            "segmentation_type_id": 52,
            "segment_num": 0,
            "segments_expected": 0,
            "sub_segment_num": 0,
            "sub_segments_expected": 0
        }
    ]
}'''

from threefive import Cue
cue=Cue()
cue.load(jason)
print(cue.encode_as_hex())
        "sap_details": "No Sap Type",
        "section_length": 59,
        "protocol_version": 0,
        "encrypted_packet": false,
        "encryption_algorithm": 0,
        "pts_adjustment_ticks": 1004614680,
        "pts_adjustment": 11162.385333,
        "cw_index": "0x00",
        "tier": "0x0fff",
        "splice_command_length": 5,
        "splice_command_type": 6,
        "descriptor_loop_length": 37,
        "crc": "0x592280ed"
    },
    "command": {
        "command_length": 5,
        "command_type": 6,
        "name": "Time Signal",
        "time_specified_flag": true,
        "pts_time": 58.52,
        "pts_time_ticks": 5266800
    },
    "descriptors": [
        {
            "tag": 2,
            "descriptor_length": 35,
            "name": "Segmentation Descriptor",
            "identifier": "CUEI",
            "segmentation_event_id": "0x02",
            "segmentation_event_cancel_indicator": false,
            "segmentation_event_id_compliance_indicator": true,
            "program_segmentation_flag": true,
            "segmentation_duration_flag": true,
            "delivery_not_restricted_flag": false,
            "web_delivery_allowed_flag": true,
            "no_regional_blackout_flag": false,
            "archive_allowed_flag": false,
            "device_restrictions": "Restrict Group 1",
            "segmentation_duration": 120.04,
            "segmentation_duration_ticks": 10803600,
            "segmentation_message": "Provider Placement Opportunity Start",
            "segmentation_upid_type": 18,
            "segmentation_upid_type_name": "Unknown",
            "segmentation_upid_length": 13,
            "segmentation_upid": "Hello, World!",
            "segmentation_type_id": 52,
            "segment_num": 0,
            "segments_expected": 0,
            "sub_segment_num": 0,
            "sub_segments_expected": 0
        }
    ]
}'''

from threefive import Cue
cue=Cue()
cue.load(jason)
print(cue.encode_as_hex())
```

**Comment by futzu** [comment]
output:

```js
0xfc303b00003be1341800fff00506fe00505d700025022343554549000000027fd10000a4d990120d48656c6c6f2c20576f726c64213400000000592280ed
```

**Comment by futzu** [comment]
Actually, you can leave the info section out, it makes that for you, and several other vars  like length and name, pts_time, you just need the pts_ticks,
Here's a bare bones json time signal with a Segmentation Descriptor.
```js
 jason ='''{

    "command": {
        "command_type": 6,
        "time_specified_flag": true,
        "pts_time_ticks": 5266800
    },
    "descriptors": [
        {
            "tag": 2,
            "segmentation_event_id": "0x02",
            "segmentation_event_cancel_indicator": false,
            "segmentation_event_id_compliance_indicator": true,
            "program_segmentation_flag": true,
            "segmentation_duration_flag": true,
            "delivery_not_restricted_flag": false,
            "web_delivery_allowed_flag": true,
            "no_regional_blackout_flag": false,
            "archive_allowed_flag": false,
            "device_restrictions": "Restrict Group 1",
            "segmentation_duration_ticks": 10803600,
            "segmentation_upid_type": 18,
            "segmentation_upid_length": 13,
            "segmentation_upid": "Hello, World!",
            "segmentation_type_id": 52,
            "segment_num": 0,
            "segments_expected": 0,
            "sub_segment_num": 0,
            "sub_segments_expected": 0
        }
    ]
}'''
from threefive import Cue
cue=Cue()
cue.load(jason)
cue.encode()
cue.show()
print(cue.encode_as_hex())
```

*  Output:
```json
{
    "info_section": {
        "table_id": "0xfc",
        "section_syntax_indicator": false,
        "private": false,
        "sap_type": "0x03",
        "sap_details": "No Sap Type",
        "section_length": 59,
        "protocol_version": 0,
        "encrypted_packet": false,
        "encryption_algorithm": 0,
        "pts_adjustment_ticks": 0,
        "cw_index": "0x0",
        "tier": "0xfff",
        "splice_command_length": 5,
        "splice_command_type": 6,
        "descriptor_loop_length": 37,
        "crc": "0x938d5054"
    },
    "command": {
        "command_length": 5,
        "command_type": 6,
        "name": "Time Signal",
        "time_specified_flag": true,
        "pts_time": 58.52,
        "pts_time_ticks": 5266800
    },
    "descriptors": [
        {
            "tag": 2,
            "descriptor_length": 35,
            "name": "Segmentation Descriptor",
            "identifier": "CUEI",
            "segmentation_event_id": "0x02",
            "segmentation_event_cancel_indicator": false,
            "segmentation_event_id_compliance_indicator": true,
            "program_segmentation_flag": true,
            "segmentation_duration_flag": true,
            "delivery_not_restricted_flag": false,
            "web_delivery_allowed_flag": true,
            "no_regional_blackout_flag": false,
            "archive_allowed_flag": false,
            "device_restrictions": "Restrict Group 1",
            "segmentation_duration_ticks": 10803600,
            "segmentation_upid_type": 18,
            "segmentation_upid_length": 13,
            "segmentation_upid": "Hello, World!",
            "segmentation_type_id": 52,
            "segment_num": 0,
            "segments_expected": 0,
            "sub_segment_num": 0,
            "sub_segments_expected": 0
        }
    ]
}
0xfc303b00000000000000fff00506fe00505d700025022343554549000000027fd10000a4d990120d48656c6c6f2c20576f726c64213400000000938d5054
```

**Comment by futzu** [comment]
Actually , you can omit the info section all together and several vars. 
```json
jason ='''{

    "command": {
        "command_type": 6,
        "time_specified_flag": true,
        "pts_time_ticks": 5266800
    },
    "descriptors": [
        {
            "tag": 2,
            "segmentation_event_id": "0x02",
            "segmentation_event_cancel_indicator": false,
            "segmentation_event_id_compliance_indicator": true,
            "program_segmentation_flag": true,
            "segmentation_duration_flag": true,
            "delivery_not_restricted_flag": false,
            "web_delivery_allowed_flag": true,
            "no_regional_blackout_flag": false,
            "archive_allowed_flag": false,
            "device_restrictions": "Restrict Group 1",
            "segmentation_duration_ticks": 10803600,
            "segmentation_upid_type": 18,
            "segmentation_upid_length": 13,
            "segmentation_upid": "Hello, World!",
            "segmentation_type_id": 52,
            "segment_num": 0,
            "segments_expected": 0,
            "sub_segment_num": 0,
            "sub_segments_expected": 0
        }
    ]
}'''
from threefive import Cue
cue=Cue()
cue.load(jason)
cue.encode()
cue.show()
print(cue.encode_as_hex())
```

* Output:
```smalltalk

{
    "info_section": {
        "table_id": "0xfc",
        "section_syntax_indicator": false,
        "private": false,
        "sap_type": "0x03",
        "sap_details": "No Sap Type",
        "section_length": 59,
        "protocol_version": 0,
        "encrypted_packet": false,
        "encryption_algorithm": 0,
        "pts_adjustment_ticks": 0,
        "cw_index": "0x0",
        "tier": "0xfff",
        "splice_command_length": 5,
        "splice_command_type": 6,
        "descriptor_loop_length": 37,
        "crc": "0x938d5054"
    },
    "command": {
        "command_length": 5,
        "command_type": 6,
        "name": "Time Signal",
        "time_specified_flag": true,
        "pts_time": 58.52,
        "pts_time_ticks": 5266800
    },
    "descriptors": [
        {
            "tag": 2,
            "descriptor_length": 35,
            "name": "Segmentation Descriptor",
            "identifier": "CUEI",
            "segmentation_event_id": "0x02",
            "segmentation_event_cancel_indicator": false,
            "segmentation_event_id_compliance_indicator": true,
            "program_segmentation_flag": true,
            "segmentation_duration_flag": true,
            "delivery_not_restricted_flag": false,
            "web_delivery_allowed_flag": true,
            "no_regional_blackout_flag": false,
            "archive_allowed_flag": false,
            "device_restrictions": "Restrict Group 1",
            "segmentation_duration_ticks": 10803600,
            "segmentation_upid_type": 18,
            "segmentation_upid_length": 13,
            "segmentation_upid": "Hello, World!",
            "segmentation_type_id": 52,
            "segment_num": 0,
            "segments_expected": 0,
            "sub_segment_num": 0,
            "sub_segments_expected": 0
        }
    ]
}
0xfc303b00000000000000fff00506fe00505d700025022343554549000000027fd10000a4d990120d48656c6c6f2c20576f726c64213400000000938d5054
a@slow:~/cuei$ 
```

**Comment by futzu** [comment]
Hey I just noticed your avail descriptor wasn't in there
fix it like this
```py3
a@slow:~/cuei$ python3
Python 3.11.9 (main, Apr 10 2024, 13:16:36) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from threefive import Cue,AvailDescriptor
>>> c =Cue("0xFC303B00003BE1341800FFF00506FE00505D700025022343554549000000027FD10000A4D990120D48656C6C6F2C20576F726C64213400000000592280ED")
>>> c.decode()
True
>>> ad =AvailDescriptor()
>>> ad.provider_avail_id=0x00000012
>>> c.descriptors.append(ad)
>>> c.encode_as_hex()
'0xfc304500003be1341800fff00506fe00505d70002f022343554549000000027fd10000a4d990120d48656c6c6f2c20576f726c6421340000000000084355454900000012e1d587c3'
```
